"""conversation hash and job dedupe

Revision ID: 0002
Revises: 0001
Create Date: 2026-10-05 18:36:11.024551
"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

revision: str = "0002"
down_revision: str | None = "0001"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # NOT NULL without defaults is safe: conversations is derived data and empty at this
    # revision (it is rebuilt by re-segmenting).

    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("conversations", sa.Column("first_message_id", sa.BigInteger(), nullable=False))
    op.add_column("conversations", sa.Column("content_hash", sa.Text(), nullable=False))
    op.add_column("jobs", sa.Column("dedupe_key", sa.Text(), nullable=True))
    op.create_index(
        "uq_jobs_pending_dedupe",
        "jobs",
        ["kind", "dedupe_key"],
        unique=True,
        postgresql_where=sa.text("status = 'pending'"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        "uq_jobs_pending_dedupe", table_name="jobs", postgresql_where=sa.text("status = 'pending'")
    )
    op.drop_column("jobs", "dedupe_key")
    op.drop_column("conversations", "content_hash")
    op.drop_column("conversations", "first_message_id")
    # ### end Alembic commands ###
