"""permission state

Revision ID: 0004
Revises: 0003
Create Date: 2026-10-05 18:55:26.988527
"""

from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

revision: str = "0004"
down_revision: str | None = "0003"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "members",
        sa.Column("guild_id", sa.BigInteger(), nullable=False),
        sa.Column("user_id", sa.BigInteger(), autoincrement=False, nullable=False),
        sa.Column("display_name", sa.Text(), nullable=False),
        sa.Column(
            "role_ids", postgresql.ARRAY(sa.BigInteger()), server_default="{}", nullable=False
        ),
        sa.Column("left_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["guild_id"], ["guilds.id"], name=op.f("fk_members_guild_id_guilds"), ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("guild_id", "user_id", name=op.f("pk_members")),
    )
    op.create_table(
        "roles",
        sa.Column("id", sa.BigInteger(), autoincrement=False, nullable=False),
        sa.Column("guild_id", sa.BigInteger(), nullable=False),
        sa.Column("name", sa.Text(), nullable=False),
        sa.Column("permissions", sa.BigInteger(), nullable=False),
        sa.ForeignKeyConstraint(
            ["guild_id"], ["guilds.id"], name=op.f("fk_roles_guild_id_guilds"), ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_roles")),
    )
    op.create_index(op.f("ix_roles_guild_id"), "roles", ["guild_id"], unique=False)
    op.create_table(
        "channel_overwrites",
        sa.Column("channel_id", sa.BigInteger(), nullable=False),
        sa.Column("target_id", sa.BigInteger(), autoincrement=False, nullable=False),
        sa.Column("target_type", sa.Text(), nullable=False),
        sa.Column("allow", sa.BigInteger(), nullable=False),
        sa.Column("deny", sa.BigInteger(), nullable=False),
        sa.CheckConstraint(
            "target_type IN ('role', 'member')", name=op.f("ck_channel_overwrites_target_type")
        ),
        sa.ForeignKeyConstraint(
            ["channel_id"],
            ["channels.id"],
            name=op.f("fk_channel_overwrites_channel_id_channels"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("channel_id", "target_id", name=op.f("pk_channel_overwrites")),
    )
    op.add_column("guilds", sa.Column("owner_id", sa.BigInteger(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("guilds", "owner_id")
    op.drop_table("channel_overwrites")
    op.drop_index(op.f("ix_roles_guild_id"), table_name="roles")
    op.drop_table("roles")
    op.drop_table("members")
    # ### end Alembic commands ###
