"""decision extraction

Revision ID: 0005
Revises: 0004
Create Date: 2026-10-06 15:55:13.462520
"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

revision: str = "0005"
down_revision: str | None = "0004"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "conversations", sa.Column("extracted_at", sa.DateTime(timezone=True), nullable=True)
    )
    op.add_column("decisions", sa.Column("decided_message_id", sa.BigInteger(), nullable=False))
    op.create_index(
        op.f("ix_decisions_supersedes_id"), "decisions", ["supersedes_id"], unique=False
    )
    # ### end Alembic commands ###
    # "Superseded" is derived from supersedes_id links at read time, never stored.
    op.drop_constraint(op.f("ck_decisions_status"), "decisions", type_="check")
    op.create_check_constraint("status", "decisions", "status IN ('proposed', 'decided')")


def downgrade() -> None:
    op.drop_constraint(op.f("ck_decisions_status"), "decisions", type_="check")
    op.create_check_constraint(
        "status", "decisions", "status IN ('proposed', 'decided', 'reversed')"
    )
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_decisions_supersedes_id"), table_name="decisions")
    op.drop_column("decisions", "decided_message_id")
    op.drop_column("conversations", "extracted_at")
    # ### end Alembic commands ###
